version: '3.1'

volumes:
  postgres:

services:
  db:
    image: 'postgres'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: presario
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped